// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vouecxkepnvylsdhdroo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvdWVjeGtlcG52eWxzZGhkcm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODc1MDksImV4cCI6MjA2NjA2MzUwOX0.6tNzaxDR8Hj0r_I-GD5Yk-rr7DMUAraUU4cC6XyaM3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);